### ISSUE TITLE
build compare doesn't check supplements and recommends

### ISSUE THREAD

**Issue by lnussel** [openSUSE/build-compare#18]
build compare doesn't check supplements and recommends, considers for example patterns-openSUSE the same even though beta test macro was changed

**Comment by olafhering** [comment]
@lnussel  Is there an easy way to verify if my change actally works?

**Comment by lnussel** [comment]
rebuilding for example patterns-openSUSE with our without the betatest macro. Or just add some supplements as only change to a spec file of some package.

**Comment by olafhering** [comment]
This works with my change.
