### ISSUE TITLE
rpmlint: skip time report

### ISSUE THREAD

**Issue by marxin** [openSUSE/build-compare#45]
I would like to enable `--time-report` in `rpmlint` that will result in the following extra output:

```

[  492s] Check time report (>1%):
[  492s]     Check                            Duration (in s)   Fraction (in %)  Checked files
[  492s]     rpm2cpio                                    44.3              31.7               
[  492s]     BuildDateCheck                              31.9              22.8         160571
[  492s]     FilesCheck                                  29.1              20.8               
[  492s]     BashismsCheck                               19.0              13.6         160571
[  492s]     FilelistCheck                                5.6               4.0               
[  492s]     SpecCheck                                    2.3               1.6               
[  492s]     TagsCheck                                    1.6               1.1               
[  492s]     TOTAL                                      139.6             100.0         160571

```

Can you please skip that in `same-build-result.sh`?
@jirislaby

**Comment by olafhering** [comment]
`rpmlint.log` is supposed to contain the state of the current binaries.

I wonder if rpmlint could add a prefix to this table. In its current form it is difficult to detect this table.

**Comment by jirislaby** [comment]
Or perl indeed:
```
perl -pe 'BEGIN {$/=undef;} s/Check time report.*TOTAL[^\n]*\n//ms'
```

**Comment by marxin** [comment]
@bmwiedemann Are you planning to work on that? I would like to enable the time report as soon as possible. Thanks.

**Comment by olafhering** [comment]
I will add code to remove it before compare old and new rpmlint.log.

In case the binaries and/or rpmlint output differ the full new log will be shown in the build results.

**Comment by olafhering** [comment]
The current state is in `openSUSE:Tools/build-compare`, please check if the awk pattern is correct.

**Comment by marxin** [comment]
I guess so, please make a SR to Factory.

**Comment by olafhering** [comment]
The change is in Tumbleweed now.
