### ISSUE TITLE
Incorrect behaviour when comparing spec files containing macro expansions in Release header

### ISSUE THREAD

**Issue by OlegGirko** [openSUSE/build-compare#5]
It's common practice for distributions other than SUSE to have macro expansions like `%{?dist}` in `Release:` header of `spec` file. Hence, I have this in my OBS project config for Fedora repos:
```
Release: <CI_CNT>%%{?dist}.<B_CNT>
```
to make built packages comply with Fedora packaging guidelines.

Unfortunately, `build-compare` doesn't handle this case correctly.
The `srpm-check.sh` file contains the following:
```bash
# Get version-release from first RPM and keep for rpmlint check
# Remember to quote the "." for future regexes
ver_rel_old=$(rpm -qp --nodigest --nosignature --qf "%{RELEASE}" "${oldrpm}"|sed -e 's/\./\\./g')
ver_rel_new=$(rpm -qp --nodigest --nosignature --qf "%{RELEASE}" "${newrpm}"|sed -e 's/\./\\./g')
...
check_single_file()
{ 
  local file=$1
  case $file in
    *.spec)
       sed -i -e "s,Release:.*${ver_rel_old}$,Release: @RELEASE@," old/$file
       sed -i -e "s,Release:.*${ver_rel_new}$,Release: @RELEASE@," new/$file
 ...
```
As a result, variables `ver_rel_old` and `ver_rel_new` contain actual versions of old and new srpm packages after all macros have been expanded, they don't match respective `Release:` headers that contain `%{?dist}` macro, so release is not replaced with `@RELEASE@` text, and `spec` files are always considered different as a result.

**Comment by olafhering** [comment]
In what project does this happen? I would like  to work with real binaries to fix this issue.

**Comment by OlegGirko** [comment]
It's happening here: https://obs.infoserver.lv/project/show/obs:server:fedora:2.6

But you can reproduce the problem in your project with the following easy steps.

* Create a project.
* Create a repo for building for Fedora (22 or 23).
* Add this to project config: `Release: <CI_CNT>%%{?dist}.<B_CNT>`
* Add `build-compare` package to your project. You can copypac it from https://obs.infoserver.lv/package/show/obs:server:fedora:2.6/build-compare
* Wait until `build-compare` is built and published.
* Add this to project config: `Support: build-compare`
* Add another package, build it and rebuild it. See how new builds don't get discarded.

**Comment by olafhering** [comment]
The regex above should probably convert also '?' into '\?'.

**Comment by olafhering** [comment]
This is a really old build-compare. I suggest to always use the one from OBS:openSUSE:Tools/build-compare because I cant reproduce it anymore. But I can with 6abe6740f72e54f18e5320669f5bff0070e8cf12

**Comment by olafhering** [comment]
Please reopen if current master still fails for you.
