### ISSUE TITLE
objdump return code regression

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/build-compare#53]
I noticed that 15-SP4's grub was reported as having 2 identical builds when there was plenty relevant objdump output.

`git bisect` pointed to 

```
38e7800e76be477b222ff85d368c12fb179183dc is the first bad commit
commit 38e7800e76be477b222ff85d368c12fb179183dc
Author: Olaf Hering <olaf@aepfle>
Date:   Sun Mar 6 12:15:16 2022 +0100

    fix ELF comparision to really show disasm output

    Also be more specific about the old/new path.

    Fixes commit e4c745cbb083481a67e852e95f5dd93ff94a82fa

```
that screwed up the return code.

**Comment by bmwiedemann** [comment]
Turther testing showed that it is [the first `elfdiff=`](https://github.com/openSUSE/build-compare/commit/38e7800e76be477b222ff85d368c12fb179183dc#diff-bd2fb7760966ea7d19833de4846b040130e7cd981e5087ea9a3a86fd793ed37fR977) that breaks the return code.

**Comment by olafhering** [comment]
Do you have a test case?
`elfdiff` seems to be indicate failure in all cases. 
Tthe variable `objdump_failed` could be removed, as it indicates some failure in the same way as `elfdiff`.
