### ISSUE TITLE
gdbus-codegen headers have to be ignored

### ISSUE THREAD

**Issue by crrodriguez** [openSUSE/build-compare#6]
Sample log :

[  178s] /usr/src/debug/udisks-2.1.6/udisks/udisks-generated.c differs (C source, ASCII text, with very long lines)
[  178s] --- old//usr/src/debug/udisks-2.1.6/udisks/udisks-generated.c	2015-12-02 03:55:57.000000000 +0000
[  178s] +++ new//usr/src/debug/udisks-2.1.6/udisks/udisks-generated.c	2015-12-10 00:24:32.000000000 +0000
[  178s] @@ -1,5 +1,5 @@
[  178s]  /*
[  178s] - * Generated by gdbus-codegen 2.46.1. DO NOT EDIT.
[  178s] + * Generated by gdbus-codegen 2.46.2. DO NOT EDIT.
[  178s]   *
[  178s]   * The license of this code is the same as for the source it was derived from.
[  178s]   */
[  178s] compare /.build.oldpackages/udisks2-devel-2.1.6-58.1.x86_64.rpm /home/abuild/rpmbuild/RPMS/x86_64/udisks2-devel-2.1.6-58.2.x86_64.rpm
[  179s] Comparing udisks2-devel-2.1.6-58.1.x86_64.rpm to udisks2-devel-2.1.6-58.2.x86_64.rpm
[  179s] comparing rpmtags
[  179s] comparing RELEASE
[  179s] comparing PROVIDES
[  179s] comparing scripts
[  179s] comparing filelist
[  179s] comparing file checksum
[  179s] creating rename script
[  179s] RPM file checksum differs.
[  179s] Extracting packages
[  180s] /usr/include/udisks2/udisks/udisks-generated.h differs (C source, ASCII text)
[  180s] --- old//usr/include/udisks2/udisks/udisks-generated.h	2015-12-02 03:56:19.000000000 +0000
[  180s] +++ new//usr/include/udisks2/udisks/udisks-generated.h	2015-12-10 00:25:08.000000000 +0000
[  180s] @@ -1,5 +1,5 @@
[  180s]  /*
[  180s] - * Generated by gdbus-codegen 2.46.1. DO NOT EDIT.
[  180s] + * Generated by gdbus-codegen 2.46.2. DO NOT EDIT.
[  180s]   *
[  180s]   * The license of this code is the same as for the source it was derived from.
[  180s]   */

the "Generated by gdbus-codegen 2.46.2. DO NOT EDIT" file header is not a change worth of republish the resulting RPMs. .

**Comment by olafhering** [comment]
There are many cases like this, many tools encode their version number into generated files. If the resulting file is easy to find/match by pathname then build-compare can handle such cases. In case of udisk it means each *.h file has to be inspected. Are there more examples like that one above?

**Comment by crrodriguez** [comment]
I guess there are many other examples.. A different solution would be to patch gdbus-codegen not to output the version number.

**Comment by olafhering** [comment]
Please patch gdbus-codegen
